
const SIGN_IN = 'SIGN_IN'
const SIGN_OUT = 'SIGN_OUT'
const CREATE_STREAM = 'CREATE_STREAM'
const EDIT_STREAM = 'EDIT_STREAM'
const FETCH_STREAMS = 'FETCH_STREAMS'
const FETCH_STREAM = 'FETCH_STEAM'
const DELETE_STREAM= 'DELETE_STREAM'

const ACTION_TYPES = {
    SIGN_IN,
    SIGN_OUT,
    CREATE_STREAM,
    EDIT_STREAM,
    FETCH_STREAMS,
    FETCH_STREAM,
    DELETE_STREAM,
}

export default ACTION_TYPES;